export const DEFAULT_LANGUAGE = 'es';
export const DEFAULT_CURRENCY = 'USD';
export const DEFAULT_AI_PROVIDER = 'claude';
export const DEFAULT_AI_MODEL = 'claude-sonnet-4-6';
export const DEFAULT_COLOR_PRIMARY = '#2563eb';
export const DEFAULT_WELCOME_MESSAGE = '¡Hola! ¿En qué puedo ayudarte hoy?';
export const DEFAULT_ESCALATION_MESSAGE = '¡Entendido! He notificado a un agente humano para que te atienda. Por favor espera, alguien se pondrá en contacto contigo pronto. ¿Hay algo más en lo que pueda ayudarte mientras esperas?';
export const DEFAULT_SYSTEM_PROMPT = 'Eres un asistente virtual útil, claro y cordial. Responde de forma concisa y servicial.';
export const DEFAULT_TENANT_NAME = 'Asistente Virtual';
